executableModuleName=kbs-backoffice-application-gwt
executableModuleVersion=1.0.0-SNAPSHOT
applicationModuleName=kbs-backoffice-application
pwa=true
mavenBuildTimestamp=${maven.build.timestamp}
environment=${webfx.meta.environment}