languages = en,fr,de,es,pt
# Overriding the menu codes to include Kadampa News & Podcasts
#mainMenuOperationCodes = RouteToHome,RouteToBooking,RouteToLibrary,RouteToVideoStreaming,RouteToNews,RouteToPodcasts,RouteToBooks,RouteToLogin,RouteToConsole
mainMenuOperationCodes = RouteToAudioLibrary,RouteToVideoStreaming,RouteToLogin

# Note that there is no default home page provided by Modality, it must be provided by the final application
startPath = /home