# Overriding menuOperationCodes to include Kadampa News & Podcasts
mainMenuOperationCodes = RouteToHome,RouteToBooking,RouteToLibrary,RouteToNews,RouteToPodcasts,RouteToLogin,RouteToConsole,Logout
userMenuOperationCodes = RouteToUserProfile,RouteToHistory,RouteToFavorites,RouteToSettings,Logout

# Note that there is no default home page provided by Modality, it must be provided by the final application
startPath = /home